FORMAT: 1A

# Labeling Tool API

# Group User
## Login [/api/v1/login]
### Login [POST]
Log a user in with mtm account and password.
+ Request (applicaiton/json)
  + Body
        {
           "account": "mtm user account",
           "password": "mtm user password"
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "username": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          }
        }


+ Response 200 (applicaiton/json)
  + Body
        {
          "token": "JSON Web Token payload"
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "token": {
              "type": "string"
            }
          }
        }

+ Response 400 (applicaiton/json)
  + Body
        {
          "message": "bad request"
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "message": {
              "type": "string"
            }
          }
        }

+ Response 401 (applicaiton/json)
  + Body
        {
          "message": "incorrect account or password"
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "message": {
              "type": "string"
            }
          }
        }

+ Response 403 (applicaiton/json)
  + Body
        {
          "message": "no permission"
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "message": {
              "type": "string"
            }
          }
        }

# Group Projects

## List Projects [/api/v1/projects?limit={limit}&offset={offset}]
### List [GET]
List all projects

+ Parameters
    + limit: `20` (number, optional) - Pagination limit. Default to 20, and maximum value is 100.
    + offset: `0` (number, optional) - Pagination offset. Default to 0.

+ Request
  + Headers
    Authorization: Bearer <token>

+ Response 200
  + Body
        {
          "total": "Numbers of all projects",
          "limit": "Current pagination limit",
          "offset": "Current pagination offset",
          "projects": [
            {
              "id": "Hashed UUID",
              "name": "Project name",
              "created_at": "Creation time",
              "updated_at": "Update time",
              "labeling_type": "Project labeling type. 0: classification only, 1: box & classification, 2: pixel-level & classification",
              "labeled": "Numbers of labeled images",
              "total": "Numbers of all images",
              "classes": "List of classes in this project"
            }
          ]
        }

  + Schema
        {
          "type": "object",
          "properties": {
            "total": {
              "type": "int"
            },
            "limit": {
              "type": "int"
            },
            "offset": {
              "type": "int"
            },
            "projects": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "created_at": {
                    "type": "datetime"
                  },
                  "updated_at": {
                    "type": "datetime"
                  },
                  "labeling_type": {
                    "type": "int"
                  },
                  "labeled": {
                    "type": "int"
                  },
                  "total": {
                    "type": "int"
                  },
                  "classes": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }


## Projects [/api/v1/projects]
### Create a project [POST]
Create a project

+ Request (applicaiton/json)
  + Headers
    Authorization: Bearer <token>

  + Body
        {
          "name": "Project name",
          "labeling_type": "Labeling Type",
          "classes": "List of class names that should be created in this project"
        }

  + Schema
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "labeling_type": {
              "type": "int"
            },
            "classes": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }

+ Response 201 (applicaiton/json)
  + Body
        {
          "id": "Hashed UUID"
        }

  + Schema
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            }
          }
        }

+ Response 400
+ Response 401
+ Response 403

## Projects [/api/v1/projects/{id}]
### Update a project [POST]
Update a project

+ Parameters
  + id: `3wZo87Bb` (string, required) - Project hashed id.

+ Request (applicaiton/json)
  + Headers
    Authorization: Bearer <token>

  + Body
        {
          "name": "(Optional) Project name",
          "labeling_type": "(Optional) Labeling Type",
          "classes": "(Optional) List of class names that should be created in this project"
        }

+ Response 200
+ Response 400
+ Response 401
+ Response 403
+ Response 404

### Delete a project [DELETE]
Delete a project

+ Parameters
  + id: `3wZo87Bb` (string, required) - Project hashed id.

+ Request
  + Headers
    Authorization: Bearer <token>

+ Response 204
+ Response 401
+ Response 403
+ Response 404

# Group Class

## Classes [/api/v1/projects/{id}/classes]
### List all classes [GET]
List all classes in a project

+ Parameters
  + id: `3wZo87Bb` (string, required) - Project hashed id.

+ Request
  + Headers
    Authorization: Bearer <token>

+ Response 200 (applicaiton/json)
  + Body
        {
          "classes": "List of classes in the project"
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "classes": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }

### Add a class [POST]
Add a class to a project

+ Parameters
  + id: `3wZo87Bb` (string, required) - Project hashed id.

+ Request (applicaiton/json)
  + Headers
    Authorization: Bearer <token>

  + Body
        {
          "name": "Name of the new class"
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
            }
          }
        }

+ Response 201 (applicaiton/json)
  + Body
        {
          "id": "Hashed class id"
        }

  + Schema
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
            }
          }
        }

+ Response 400
+ Response 401
+ Response 403
+ Response 404

## Classes [/api/v1/classes/{id}]
### Update a class [POST]
Update a class

+ Parameters
  + id: `3wZo87Bb` (string, required) - Class hashed id.

+ Request (applicaiton/json)
  + Headers
    Authorization: Bearer <token>

  + Body
        {
          "name": "New name of the class"
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
            }
          }
        }

+ Response 200
+ Response 400
+ Response 401
+ Response 403
+ Response 404

### Delete a class [DELETE]
Delete a class

+ Parameters
  + id: `3wZo87Bb` (string, required) - Class hashed id.

+ Request
  + Headers
    Authorization: Bearer <token>

+ Response 204
+ Response 401
+ Response 403
+ Response 404

# Group Image
## Images [/api/v1/projects/{id}/images?limit={limit}&offset={offset}&label={label}]
### List all images [GET]

+ Parameters
  + id: `3wZo87Bb` (string, required) - Project hashed id.
  + limit: `20` (number, optional) - Pagination limit. Default to 20, and maximum value is 100.
  + offset: `0` (number, optional) - Pagination offset. Default to 0.
  + label: `true` (boolean, optional) - Should only list images that need to be labeled. Default to false.

+ Request
  + Headers
    Authorization: Bearer <token>

+ Response 200 (applicaiton/json)
  + Body
        {
          "total": "Numbers of all images in this project",
          "offset": "Current pagination offset",
          "limit": "Current pagination limit",
          "images": [
            {
              "id": "Image hashed id",
              "file_name": "File name",
              "file_path": "Signed url of the image",
              "status": "Label status. 0: not uploaded, 1: not labeled, 2: labeled",
              "md5": "MD5 of the image",
              "labeled_at": "Last labeled time"
            }
          ]
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "total": {
              "type": "int",
            },
            "offset": {
              "type": "int",
            },
            "limit": {
              "type": "int",
            },
            "images": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "file_name": {
                    "type": "string"
                  },
                  "file_path": {
                    "type": "string"
                  },
                  "status": {
                    "type": "int"
                  },
                  "md5": {
                    "type": "string"
                  },
                  "labeled_at": {
                    "type": "datetime"
                  }
                }
              }
            }
          }
        }
+ Response 401
+ Response 403
+ Response 404

## Images [/api/v1/images/{id}/label]
### Label an image [POST]

+ Parameters
  + id: `3wZo87Bb` (string, required) - Image hashed id.

+ Request
  + Headers
    Authorization: Bearer <token>
  + Body
    Use empty body to skip labeling.

+ Request (applicaiton/json)
  + Headers
    Authorization: Bearer <token>

  + Body
        {
          "labels": [
            {
              "class_id": "Class hashed id",
              "bbox": "Stringified xy positions"
            }
          ]
        }

  + Schema
        {
          "type": "object",
          "properties": {
            "labels": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "class_id": {
                    "type": "string"
                  },
                  "bbox": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }

+ Response 200
  + Body
        {
          "next": {
            "id": "Image hashed id",
            "file_name": "File name",
            "file_path": "Signed url of the image",
            "status": "Label status. 0: not uploaded, 1: not labeled, 2: labeled",
            "md5": "MD5 of the image",
            "labeled_at": "Last labeled time"
          }
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "next": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "file_name": {
                  "type": "string"
                },
                "file_path": {
                  "type": "string"
                },
                "status": {
                  "type": "int"
                },
                "md5": {
                  "type": "string"
                },
                "labeled_at": {
                  "type": "datetime"
                }
              }
            }
          }
        }

+ Response 200
  + Body
        {
          "next": null
        }
  + Schema
        {
          "type": "object",
          "properties": {
            "next": {
              "type": "null"
            }
          }
        }
+ Response 400
+ Response 401
+ Response 403
+ Response 404
